# Generated by Django 5.2.3 on 2025-06-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_description_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
